# Dataset name
DATASET_DIR: "$DATASET_DIR" # '/Users/menga/Desktop/github/zsl_taglets/development' #
DATASET_NAME: "$DATASET_NAME"
# Model
MODALITY: 'image'
MODEL: "$MODEL"
# Visual ecoder
VIS_ENCODER: "$VIS_ENCODER"
# Prompt template
PROMPT_TEMPLATE: 'imported in main.py'
# Number of shats per classes in SSL
N_LABEL: 16
ALPHA: 0.3
# Prefix size
PREFIX_SIZE: 16
# Prefix initialization: normal/uniform
VIS_PREFIX_INIT: "normal"
# Initialization mean and variance
MEAN_INIT: 0
VAR_INIT: 0.02
# Seeed to separate train and validation
validation_seed: 0
# Ratio validation
ratio_train_val: 0.5
# Batch size
BATCH_SIZE: 16
# Number of epochs
EPOCHS: 100 #100
# Scheduler
SCHEDULER: "cosine"
# Scheduler warmup epochs
WARMUP_EPOCHS: 5
WARMUP_LR: 0.0001
# Number of accumulation iter
ACCUMULATION_ITER: 1
# Optimizer
OPTIM: "SGD"
LR: 0.1 # 0.1
DECAY: 0.1 # 0.1
STEP_SIZE: 1
# Set seeds
OPTIM_SEED: "$OPTIM_SEED"
# Classes split
CLASSES_SPLIT: SPLIT_SEED
# Seed split
SPLIT_SEED: "$SPLIT_SEED"


META_EPOCHS: 250 # 250
META_LR: 0.02 #0.02
BETA: 0.9 #0.9
N_HID: 32 # 32
TAU: 0.01 # 0.01
fusion: "mul"